---
- name: "Pre-setup: Ensure pip is present"
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: "Pre-setup: Install mktxp system-wide"
  ansible.builtin.pip:
    name: mktxp
    executable: pip3
