---
- name: remount filesystems
  ansible.posix.mount:
    state: remounted
    name: "{{ base_virtiofs_mount_base_mountpoint }}/{{ mount.mount_point }}"
    fstype: "{{ mount.fstype | default('virtiofs') }}"
    src: "{{ mount.src | default(mount.target_dir) }}"
    opts: "{{ mount.opts | default('defaults') }}"
  loop: "{{ base_virtiofs_mounts }}"
  loop_control:
    loop_var: "mount"
