---
services_jenkins_repo_key: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
services_jenkins_repo: "deb https://pkg.jenkins.io/debian-stable binary/"
services_jenkins_home: "/var/lib/jenkins"

services_jenkins_java_options: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"'
services_jenkins_startup_timeout: 300
services_jenkins_user: "jenkins"
services_jenkins_systemd_file: "/lib/systemd/system/jenkins.service"

# Default username/password. Should be overriden
services_jenkins_admin_user: "admin"
services_jenkins_admin_pass: "admin"

services_jenkins_username_password_credentials: []
services_jenkins_secret_text_credentials: []
services_jenkins_ssh_credentials: []

services_jenkins_plugins: []
