---
services_jenkins_packages:
  - apt-transport-https
  - curl
  - genisoimage
  - gnupg
  - libguestfs-tools
  - libvirt-dev
  - openjdk-21-jdk
  - python3-jmespath
  - python3-netaddr
  - qemu-kvm
  - xsltproc

