---
- name: "Pre-setup: Download splunk server"
  ansible.builtin.get_url:
    url: "https://download.splunk.com/products/splunk/releases/10.2.0/linux/splunk-10.2.0-d749cb17ea65-linux-amd64.deb"
    dest: "/tmp"
    mode: '0700'
