---
base_vmhost_packages:
# Basic packages for QEMU/KVM
  - bridge-utils
  - qemu-kvm
  - libvirt-clients
  - libguestfs-tools
  - virt-manager
# Extra packages for host management
  - xutils
  - cpu-checker
# Ansible related packages and their python3 versions
  - python3-libvirt
  - python3-lxml
# I want this for EMBY
  - ffmpeg
  - screen
# I want this for the filetransfer work
  - nfs-common
  - unrar
  - mkvtoolnix
# Now zfs is what i also need
  - zfsutils-linux
# That's a nice tool to have in baremetal servers
  - smartmontools
  - sysstat
